### ISSUE TITLE
Could I use this package to transform RTSP stream into a browser playable format?

### ISSUE THREAD

**Issue by ken1234l** [LostBeard/SpawnDev.BlazorJS.FFmpegWasm#1]
I see the sample that can use ffmpeg to transform  file to playable stream, if it work to change the input into a RTSP stream??  I need to read the video stream and show on blazor wasm.

**Comment by LostBeard** [comment]
Short answer: I do not think so at this time.

I did some quick searching and unfortunately there doesn't seem to be a way for a web browser to connect to an RTSP endpoint. Even if ffmpeg.wasm could transcode RTSP to a ```<video>``` usable stream, it seems the browser cannot connect to an RTSP source without some sort of proxy. (ffmpeg.wasm has the same limits as Javascript and therefore no WebSocket support which I believe is needed.)

References:  
[[RTSP solution for JavaScript/HTML5](https://stackoverflow.com/questions/24440265/rtsp-solution-for-javascript-html5)](https://stackoverflow.com/questions/24440265/rtsp-solution-for-javascript-html5)

[html5_rtsp_player](https://github.com/Streamedian/html5_rtsp_player)   
A project that can remux a proxied RTSP stream into one usable by a ```<video>``` element. 

Another proxy based project:  
[h5stream](https://github.com/linkingvision/h5stream)

And another:  
[RTSPtoWeb](https://github.com/deepch/RTSPtoWeb)

This simple Javascript code example looked a little promising. But a bit basic, so maybe not useful or others would have mentioned it.
[HTML5 video web RTSP](https://codepen.io/headmax/pen/mpNvKM?editors=1111)

I couldn't find a public rtsp:// link to use for testing. If you find one please let me know. I used VLC to create an rtsp:// stream to do some basic tests with XMLHTTPRequest (like in the above link) but CORS issues prevented that from getting very far.

If I find anything else useful for this I will post back here. If you find anything that may help I am willing to take a look.
