### ISSUE TITLE
How to read SpawnDev.BlazorJS.JSObjects.File from WorkerFS?

### ISSUE THREAD

**Issue by Alicg** [LostBeard/SpawnDev.BlazorJS.FFmpegWasm#2]
Hi, thanks for a great library.

I use ffmpeg.MountWorkerFS to mount user's files into ffmpeg file system:
await ffmpeg.MountWorkerFS(inputDir, new FSMountWorkerFSOptions { Files = new[] { file1, file2 } });

After the conversion, I want to read the output video file not as a byte array, but as SpawnDev.BlazorJS.JSObjects.File so I can reuse it for future ffmpeg.MountWorkerFS calls. Is it possible and if not, how can I create a new SpawnDev.BlazorJS.JSObjects.File using byte array read from WorkerFS?

**Comment by LostBeard** [comment]
If you want to do more processing immediately, use the output file path as the next call's input file path. 

To create a SpawnDev.BlazorJS.JSObjects.File instance see the examples below.
```cs
using var data = await ffmpeg.ReadFileUint8Array(outputFile);
var file = new File([data], "filename.mp4", new JSObjects.FileOptions { Type = "video/mp4" });
// use file ...
```
Or using a Blob intermediate
```cs
using var data = await ffmpeg.ReadFileUint8Array(outputFile);
using var blob = new Blob(new Uint8Array[] { data }, new BlobOptions { Type = "video/mp4" });
var file = new File([ blob ], "filename.mp4");
// use file ...
```
